// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSharpGenerator.Web.Database
{
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class AppDbContext : AppDbContextBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data.Entity;\r\nusin" +
                    "g System.Linq;\r\nusing System.Web;\r\nusing System.Data.Entity.ModelConfiguration.C" +
                    "onventions;\r\nusing ");
            
            #line 9 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbContextNamespace));
            
            #line default
            #line hidden
            this.Write(".Mapping;\r\n\r\n");
            
            #line 11 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"

string baseClassName;
if (String.Equals(DbContextType, "DbContext", StringComparison.Ordinal))
{
   baseClassName = "System.Data.Entity.DbContext";
}
else
{
   baseClassName = "DbContext";
}

            
            #line default
            #line hidden
            
            #line 22 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
 if (!String.IsNullOrEmpty(DbContextNamespace)) { 
            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 23 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbContextNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 25 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
 
PushIndent("    ");
} 

            
            #line default
            #line hidden
            this.Write("public class ");
            
            #line 29 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbContextType));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 29 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseClassName));
            
            #line default
            #line hidden
            this.Write(@"
{
    // You can add custom code to this file. Changes will not be overwritten.
    // 
    // If you want Entity Framework to drop and regenerate your database
    // automatically whenever you change your model schema, please use data migrations.
    // For more information refer to the documentation:
    // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
    public ");
            
            #line 38 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbContextType));
            
            #line default
            #line hidden
            this.Write("() : base(\"name=");
            
            #line 38 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConnectionStringName));
            
            #line default
            #line hidden
            this.Write("\")\r\n    {\r\n        Database.SetInitializer<");
            
            #line 40 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DbContextType));
            
            #line default
            #line hidden
            this.Write(">(null);\r\n    }\r\n\r\n    protected override void OnModelCreating(DbModelBuilder mod" +
                    "elbuilder)\r\n    {\r\n        modelbuilder.Conventions.Remove<PluralizingTableNameC" +
                    "onvention>();\r\n\r\n        //Model Mapping\r\n        ");
            
            #line 48 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"

    foreach(var entity in EntityMembers){
        
            
            #line default
            #line hidden
            this.Write("        modelbuilder.Configurations.Add(new ");
            
            #line 51 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("Map());\r\n        ");
            
            #line 52 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"

    }
        
            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    ");
            
            #line 57 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"

        foreach(var entity in EntityMembers){
    
            
            #line default
            #line hidden
            this.Write("\r\n    public System.Data.Entity.DbSet<");
            
            #line 61 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.EntityTypeName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 61 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.EntityTypeNamePluralized));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\r\n    ");
            
            #line 63 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
    } 
            
            #line default
            #line hidden
            this.Write("\r\n}\r\n");
            
            #line 66 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
 if (!String.IsNullOrEmpty(DbContextNamespace)) { 
ClearIndent();

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 70 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"
 
} 

            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 75 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Database\AppDbContext.tt"

    public string DbContextNamespace{set;get;}
    public string DbContextType{set;get;}
    public string ConnectionStringName{set;get;}

    public class EntityMember{
        public string EntityTypeName{get;set;}
        public string EntityTypeNamePluralized{get;set;}
    }

    public List<EntityMember> EntityMembers{get;set;}
 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class AppDbContextBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
