// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AppsGenerator.CSharpGenerator.Web.MvcControllerWithContext
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Microsoft.AspNet.Scaffolding.Core.Metadata;
    using Microsoft.AspNet.Scaffolding;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class Controller : ControllerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 5 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"

string routePrefix;
if (String.IsNullOrEmpty(AreaName)) 
{
    routePrefix = ControllerRootName;
}
else
{
    routePrefix = AreaName + "/" + ControllerRootName;
}

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data.Entity;\r\nusin" +
                    "g System.Linq;\r\n");
            
            #line 24 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("using System.Threading.Tasks;\r\n");
            
            #line 26 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("using System.Net;\r\nusing System.Web;\r\nusing System.Web.Mvc;\r\nusing ");
            
            #line 30 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(".Models;\r\nusing PagedList;\r\n");
            
            #line 32 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 foreach (var namespaceName in RequiredNamespaces) { 
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 33 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 34 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 36 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(".Controllers\r\n{\r\n");
            
            #line 38 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"

    var contextTypeName = ContextTypeName;
    var entitySetName = ModelMetadata.EntitySetName;
    var entitySetVar = EntitySetVariable ?? (String.IsNullOrEmpty(entitySetName) ? entitySetName : (entitySetName.Substring(0, 1).ToLowerInvariant() + entitySetName.Substring(1)));
    var primaryKeyName = ModelMetadata.PrimaryKeys[0].PropertyName;
    var primaryKeyShortTypeName = ModelMetadata.PrimaryKeys[0].ShortTypeName;
    var primaryKeyDefaultValue = ModelMetadata.PrimaryKeys[0].DefaultValue;
    var primaryKeyType = ModelMetadata.PrimaryKeys[0].TypeName;
    var primaryKeyNullableTypeName = GetNullableTypeName(primaryKeyType, primaryKeyShortTypeName);
    var lambdaVar = ModelVariable.ToLower()+"Exp";
    var relatedProperties = ModelMetadata.RelatedEntities.ToDictionary(item => item.AssociationPropertyName);

    string bindAttribute;
    if (IsOverpostingProtectionRequired)
    {
        bindAttribute = String.Format("[Bind(Include = \"{0}\")] ", BindAttributeIncludeText);
    }
    else
    {
        bindAttribute = String.Empty;
    }

            
            #line default
            #line hidden
            this.Write("    public class ");
            
            #line 60 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ControllerName));
            
            #line default
            #line hidden
            this.Write(" : Controller\r\n    {\r\n        private ");
            
            #line 62 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextTypeName));
            
            #line default
            #line hidden
            this.Write(" db = new ");
            
            #line 62 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ContextTypeName));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n        // GET: ");
            
            #line 64 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routePrefix));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 65 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("        public async Task<ActionResult> Index()\r\n");
            
            #line 67 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public ActionResult Index(int? page)\r\n");
            
            #line 69 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            int pageSize = 3;\r\n            int pageNumber = (page ?? 1" +
                    ");\r\n");
            
            #line 73 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
  var includeExpressions = "";
        includeExpressions = String.Join("", relatedProperties.Values.Select(property => String.Format(".Include({0} => {0}.{1})", lambdaVar, property.AssociationPropertyName)));

            
            #line default
            #line hidden
            this.Write("      \r\n");
            
            #line 76 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if(!String.IsNullOrEmpty(includeExpressions)) { 
            
            #line default
            #line hidden
            this.Write("            var ");
            
            #line 77 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetVar));
            
            #line default
            #line hidden
            this.Write(" = db.");
            
            #line 77 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(includeExpressions));
            
            #line default
            #line hidden
            this.Write(".ToList();\r\n");
            
            #line 78 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
		if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("            return View(await ");
            
            #line 79 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetVar));
            
            #line default
            #line hidden
            this.Write(".ToListAsync());\r\n");
            
            #line 80 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
		} else { 
            
            #line default
            #line hidden
            this.Write("            return View(");
            
            #line 81 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetVar));
            
            #line default
            #line hidden
            this.Write(".ToPagedList(pageNumber, pageSize));\r\n");
            
            #line 82 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
		} 
            
            #line default
            #line hidden
            
            #line 83 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 84 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
		if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("            return View(await db.");
            
            #line 85 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            
            #line 85 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(includeExpressions));
            
            #line default
            #line hidden
            this.Write(".ToListAsync());\r\n");
            
            #line 86 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
		} else { 
            
            #line default
            #line hidden
            this.Write("            return View(db.");
            
            #line 87 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            
            #line 87 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(includeExpressions));
            
            #line default
            #line hidden
            this.Write(".ToList().ToPagedList(pageNumber, pageSize));\r\n");
            
            #line 88 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
		} 
            
            #line default
            #line hidden
            
            #line 89 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        // GET: ");
            
            #line 92 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routePrefix));
            
            #line default
            #line hidden
            this.Write("/Details/5\r\n");
            
            #line 93 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("        public async Task<ActionResult> Details(");
            
            #line 94 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyNullableTypeName));
            
            #line default
            #line hidden
            this.Write(" id)\r\n");
            
            #line 95 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public ActionResult Details(");
            
            #line 96 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyNullableTypeName));
            
            #line default
            #line hidden
            this.Write(" id)\r\n");
            
            #line 97 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            if (id == null)\r\n            {\r\n                return new" +
                    " HttpStatusCodeResult(HttpStatusCode.BadRequest);\r\n            }\r\n");
            
            #line 103 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 104 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 104 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" = await db.");
            
            #line 104 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".FindAsync(id);\r\n");
            
            #line 105 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 106 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 106 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" = db.");
            
            #line 106 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".Find(id);\r\n");
            
            #line 107 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 108 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return HttpNotFound();\r\n            }\r\n" +
                    "            return View(");
            
            #line 112 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        // GET: ");
            
            #line 115 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routePrefix));
            
            #line default
            #line hidden
            this.Write("/Create\r\n        public ActionResult Create()\r\n        {\r\n");
            
            #line 118 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 foreach (var property in relatedProperties.Values) { 
            
            #line default
            #line hidden
            this.Write("            ViewBag.");
            
            #line 119 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ForeignKeyPropertyNames[0]));
            
            #line default
            #line hidden
            this.Write(" = new SelectList(db.");
            
            #line 119 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.EntitySetName));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 119 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PrimaryKeyNames[0]));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 119 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DisplayPropertyName));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 120 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            return View();\r\n        }\r\n\r\n        // POST: ");
            
            #line 124 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routePrefix));
            
            #line default
            #line hidden
            this.Write("/Create\r\n");
            
            #line 125 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (IsOverpostingProtectionRequired) {
    foreach (var line in OverpostingWarningMessage.Split(new string[] { Environment.NewLine }, StringSplitOptions.None)) { 

            
            #line default
            #line hidden
            this.Write("        // ");
            
            #line 128 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 129 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("        [HttpPost]\r\n        [ValidateAntiForgeryToken]\r\n");
            
            #line 132 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("        public async Task<ActionResult> Create(");
            
            #line 133 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bindAttribute));
            
            #line default
            #line hidden
            
            #line 133 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 133 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 134 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public ActionResult Create(");
            
            #line 135 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bindAttribute));
            
            #line default
            #line hidden
            
            #line 135 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 135 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 136 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            if (ModelState.IsValid)\r\n            {\r\n");
            
            #line 140 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if(!String.IsNullOrEmpty(primaryKeyType) && String.Equals("System.Guid", primaryKeyType, StringComparison.OrdinalIgnoreCase)) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 141 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 141 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyName));
            
            #line default
            #line hidden
            this.Write(" = Guid.NewGuid();\r\n");
            
            #line 142 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                db.");
            
            #line 143 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".Add(");
            
            #line 143 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 144 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) {
            
            #line default
            #line hidden
            this.Write("                await db.SaveChangesAsync();\r\n");
            
            #line 146 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                db.SaveChanges();\r\n");
            
            #line 148 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                return RedirectToAction(\"Index\");\r\n            }\r\n\r\n");
            
            #line 152 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 foreach (var property in relatedProperties.Values) { 
            
            #line default
            #line hidden
            this.Write("            ViewBag.");
            
            #line 153 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ForeignKeyPropertyNames[0]));
            
            #line default
            #line hidden
            this.Write(" = new SelectList(db.");
            
            #line 153 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.EntitySetName));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 153 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PrimaryKeyNames[0]));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 153 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DisplayPropertyName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 153 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 153 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ForeignKeyPropertyNames[0]));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 154 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            return View(");
            
            #line 155 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        // GET: ");
            
            #line 158 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routePrefix));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n");
            
            #line 159 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("        public async Task<ActionResult> Edit(");
            
            #line 160 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyNullableTypeName));
            
            #line default
            #line hidden
            this.Write(" id)\r\n");
            
            #line 161 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public ActionResult Edit(");
            
            #line 162 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyNullableTypeName));
            
            #line default
            #line hidden
            this.Write(" id)\r\n");
            
            #line 163 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            if (id == null)\r\n            {\r\n                return new" +
                    " HttpStatusCodeResult(HttpStatusCode.BadRequest);\r\n            }\r\n");
            
            #line 169 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 170 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 170 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" = await db.");
            
            #line 170 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".FindAsync(id);\r\n");
            
            #line 171 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 172 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 172 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" = db.");
            
            #line 172 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".Find(id);\r\n");
            
            #line 173 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 174 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return HttpNotFound();\r\n            }\r\n" +
                    "");
            
            #line 178 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 foreach (var property in relatedProperties.Values) { 
            
            #line default
            #line hidden
            this.Write("            ViewBag.");
            
            #line 179 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ForeignKeyPropertyNames[0]));
            
            #line default
            #line hidden
            this.Write(" = new SelectList(db.");
            
            #line 179 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.EntitySetName));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 179 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PrimaryKeyNames[0]));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 179 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DisplayPropertyName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 179 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 179 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ForeignKeyPropertyNames[0]));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 180 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            return View(");
            
            #line 181 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        // POST: ");
            
            #line 184 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routePrefix));
            
            #line default
            #line hidden
            this.Write("/Edit/5\r\n");
            
            #line 185 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (IsOverpostingProtectionRequired) {
    foreach (var line in OverpostingWarningMessage.Split(new string[] { Environment.NewLine }, StringSplitOptions.None)) { 

            
            #line default
            #line hidden
            this.Write("        // ");
            
            #line 188 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 189 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("        [HttpPost]\r\n        [ValidateAntiForgeryToken]\r\n");
            
            #line 192 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("        public async Task<ActionResult> Edit(");
            
            #line 193 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bindAttribute));
            
            #line default
            #line hidden
            
            #line 193 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 193 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 194 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public ActionResult Edit(");
            
            #line 195 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(bindAttribute));
            
            #line default
            #line hidden
            
            #line 195 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 195 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 196 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            if (ModelState.IsValid)\r\n            {\r\n                db" +
                    ".Entry(");
            
            #line 200 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(").State = EntityState.Modified;\r\n");
            
            #line 201 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("                await db.SaveChangesAsync();\r\n");
            
            #line 203 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                db.SaveChanges();\r\n");
            
            #line 205 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                return RedirectToAction(\"Index\");\r\n            }\r\n");
            
            #line 208 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 foreach (var property in relatedProperties.Values) { 
            
            #line default
            #line hidden
            this.Write("            ViewBag.");
            
            #line 209 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ForeignKeyPropertyNames[0]));
            
            #line default
            #line hidden
            this.Write(" = new SelectList(db.");
            
            #line 209 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.EntitySetName));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 209 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.PrimaryKeyNames[0]));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 209 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DisplayPropertyName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 209 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 209 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.ForeignKeyPropertyNames[0]));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 210 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            return View(");
            
            #line 211 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        // GET: ");
            
            #line 214 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routePrefix));
            
            #line default
            #line hidden
            this.Write("/Delete/5\r\n");
            
            #line 215 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("        public async Task<ActionResult> Delete(");
            
            #line 216 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyNullableTypeName));
            
            #line default
            #line hidden
            this.Write(" id)\r\n");
            
            #line 217 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public ActionResult Delete(");
            
            #line 218 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyNullableTypeName));
            
            #line default
            #line hidden
            this.Write(" id)\r\n");
            
            #line 219 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n            if (id == null)\r\n            {\r\n                return new" +
                    " HttpStatusCodeResult(HttpStatusCode.BadRequest);\r\n            }\r\n");
            
            #line 225 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 226 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 226 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" = await db.");
            
            #line 226 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".FindAsync(id);\r\n");
            
            #line 227 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 228 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 228 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" = db.");
            
            #line 228 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".Find(id);\r\n");
            
            #line 229 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            if (");
            
            #line 230 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return HttpNotFound();\r\n            }\r\n" +
                    "            return View(");
            
            #line 234 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        // POST: ");
            
            #line 237 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(routePrefix));
            
            #line default
            #line hidden
            this.Write("/Delete/5\r\n        [HttpPost, ActionName(\"Delete\")]\r\n        [ValidateAntiForgery" +
                    "Token]\r\n");
            
            #line 240 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("        public async Task<ActionResult> DeleteConfirmed(");
            
            #line 241 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyShortTypeName));
            
            #line default
            #line hidden
            this.Write(" id)\r\n");
            
            #line 242 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("        public ActionResult DeleteConfirmed(");
            
            #line 243 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primaryKeyShortTypeName));
            
            #line default
            #line hidden
            this.Write(" id)\r\n");
            
            #line 244 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        {\r\n");
            
            #line 246 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 247 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 247 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" = await db.");
            
            #line 247 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".FindAsync(id);\r\n");
            
            #line 248 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 249 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 249 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(" = db.");
            
            #line 249 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".Find(id);\r\n");
            
            #line 250 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            db.");
            
            #line 251 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entitySetName));
            
            #line default
            #line hidden
            this.Write(".Remove(");
            
            #line 251 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelVariable));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 252 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 if (UseAsync) { 
            
            #line default
            #line hidden
            this.Write("            await db.SaveChangesAsync();\r\n");
            
            #line 254 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("            db.SaveChanges();\r\n");
            
            #line 256 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            return RedirectToAction(""Index"");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
");
            return this.GenerationEnvironment.ToString();
        }
        private global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost hostValue;
        /// <summary>
        /// The current host for the text templating engine
        /// </summary>
        public virtual global::Microsoft.VisualStudio.TextTemplating.ITextTemplatingEngineHost Host
        {
            get
            {
                return this.hostValue;
            }
            set
            {
                this.hostValue = value;
            }
        }
        
        #line 270 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"

// This function converts the primary key short type name to its nullable equivalent when possible. This is required to make
// sure that an HTTP 400 error is thrown when the user tries to access the edit, delete, or details action with null values.
    string GetNullableTypeName(string typeName, string shortTypeName)
    {
        // The exceptions are caught because if for any reason the type is user defined, then the short type name will be used.
        // In that case the user will receive a server error if null is passed to the edit, delete, or details actions.
        Type primaryKeyType = null;
        try
        {
            primaryKeyType = Type.GetType(typeName);
        }
        catch
        {
        }
        if (primaryKeyType != null && (primaryKeyType.IsPrimitive || IsGuid(typeName)))
        {
            return shortTypeName + "?";
        }
        return shortTypeName;
    }

    bool IsGuid(string typeName) {
        return String.Equals("System.Guid", typeName, StringComparison.OrdinalIgnoreCase);
    }

        
        #line default
        #line hidden
        
        #line 299 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\AppsGenerator\CSharpGenerator\Web\MvcControllerWithContext\Controller.tt"


    public string ControllerName{get;set;}
    public string ControllerRootName{get;set;}
    public string Namespace{get;set;}
    public string AreaName{get;set;}
    public string ContextTypeName{get;set;}
    public string ModelTypeName{get;set;}
    public string ModelVariable{get;set;}
    public Microsoft.AspNet.Scaffolding.Core.Metadata.ModelMetadata ModelMetadata{get;set;}
    public string EntitySetVariable{get;set;}
    public bool UseAsync{get;set;}
    public bool IsOverpostingProtectionRequired{get;set;}
    public string BindAttributeIncludeText{get;set;}
    public string OverpostingWarningMessage{get;set;}
    public System.Collections.Generic.HashSet<System.String> RequiredNamespaces{get;set;}

 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ControllerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
