// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSharpGenerator.Web.Configuration
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Configuration\WebConfig.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class WebConfig : WebConfigBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<?xml version=""1.0"" encoding=""utf-8""?>
<!--
  For more information on how to configure your ASP.NET application, please visit
  http://go.microsoft.com/fwlink/?LinkId=301880
  -->
<configuration>
<configSections>
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name=""entityFramework"" type=""System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"" requirePermission=""false"" />
  </configSections>
  <appSettings>
    <add key=""webpages:Version"" value=""3.0.0.0""/>
    <add key=""webpages:Enabled"" value=""false""/>
    <add key=""ClientValidationEnabled"" value=""true""/>
    <add key=""UnobtrusiveJavaScriptEnabled"" value=""true""/>
  </appSettings>

  <connectionStrings>
    <add name=""");
            
            #line 24 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Configuration\WebConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppName));
            
            #line default
            #line hidden
            this.Write("Entities\" connectionString=\"");
            
            #line 24 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Configuration\WebConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConnectionString));
            
            #line default
            #line hidden
            this.Write(";App=EntityFramework\" providerName=\"System.Data.SqlClient\" />\r\n  </connectionStri" +
                    "ngs>\r\n  <entityFramework>\r\n    <defaultConnectionFactory type=\"System.Data.Entit" +
                    "y.Infrastructure.LocalDbConnectionFactory, EntityFramework\">\r\n      <parameters>" +
                    "\r\n        <parameter value=\"v11.0\" />\r\n      </parameters>\r\n    </defaultConnect" +
                    "ionFactory>\r\n    <providers>\r\n      <provider invariantName=\"System.Data.SqlClie" +
                    "nt\" type=\"System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlS" +
                    "erver\" />\r\n    </providers>\r\n  </entityFramework>\r\n\r\n  <system.web>\r\n    <compil" +
                    "ation debug=\"true\" targetFramework=\"4.5\">\r\n\r\n      <assemblies>\r\n        <add as" +
                    "sembly=\"System.Data.Entity, Version=4.0.0.0, Culture=neutral,\r\n           Public" +
                    "KeyToken=b77a5c561934e089\" />\r\n      </assemblies>\r\n      \r\n    </compilation>\r\n" +
                    "    <httpRuntime targetFramework=\"4.5\"/>\r\n  </system.web>\r\n  <runtime>\r\n    <ass" +
                    "emblyBinding xmlns=\"urn:schemas-microsoft-com:asm.v1\">\r\n      <dependentAssembly" +
                    ">\r\n        <assemblyIdentity name=\"Microsoft.Owin\" publicKeyToken=\"31bf3856ad364" +
                    "e35\"/>\r\n        <bindingRedirect oldVersion=\"1.0.0.0-3.0.0.0\" newVersion=\"3.0.0." +
                    "0\"/>\r\n      </dependentAssembly>\r\n      <dependentAssembly>\r\n        <assemblyId" +
                    "entity name=\"Microsoft.Owin.Security.OAuth\" publicKeyToken=\"31bf3856ad364e35\"/>\r" +
                    "\n        <bindingRedirect oldVersion=\"1.0.0.0-3.0.0.0\" newVersion=\"3.0.0.0\"/>\r\n " +
                    "     </dependentAssembly>\r\n      <dependentAssembly>\r\n        <assemblyIdentity " +
                    "name=\"Microsoft.Owin.Security.Cookies\" publicKeyToken=\"31bf3856ad364e35\"/>\r\n    " +
                    "    <bindingRedirect oldVersion=\"1.0.0.0-3.0.0.0\" newVersion=\"3.0.0.0\"/>\r\n      " +
                    "</dependentAssembly>\r\n      <dependentAssembly>\r\n        <assemblyIdentity name=" +
                    "\"Microsoft.Owin.Security\" publicKeyToken=\"31bf3856ad364e35\"/>\r\n        <bindingR" +
                    "edirect oldVersion=\"1.0.0.0-3.0.0.0\" newVersion=\"3.0.0.0\"/>\r\n      </dependentAs" +
                    "sembly>\r\n      <dependentAssembly>\r\n        <assemblyIdentity name=\"Newtonsoft.J" +
                    "son\" culture=\"neutral\" publicKeyToken=\"30ad4fe6b2a6aeed\"/>\r\n        <bindingRedi" +
                    "rect oldVersion=\"0.0.0.0-6.0.0.0\" newVersion=\"6.0.0.0\"/>\r\n      </dependentAssem" +
                    "bly>\r\n      <dependentAssembly>\r\n        <assemblyIdentity name=\"System.Web.Opti" +
                    "mization\" publicKeyToken=\"31bf3856ad364e35\"/>\r\n        <bindingRedirect oldVersi" +
                    "on=\"1.0.0.0-1.1.0.0\" newVersion=\"1.1.0.0\"/>\r\n      </dependentAssembly>\r\n      <" +
                    "dependentAssembly>\r\n        <assemblyIdentity name=\"WebGrease\" publicKeyToken=\"3" +
                    "1bf3856ad364e35\"/>\r\n        <bindingRedirect oldVersion=\"1.0.0.0-1.5.2.14234\" ne" +
                    "wVersion=\"1.5.2.14234\"/>\r\n      </dependentAssembly>\r\n      <dependentAssembly>\r" +
                    "\n        <assemblyIdentity name=\"System.Web.Helpers\" publicKeyToken=\"31bf3856ad3" +
                    "64e35\"/>\r\n        <bindingRedirect oldVersion=\"1.0.0.0-3.0.0.0\" newVersion=\"3.0." +
                    "0.0\"/>\r\n      </dependentAssembly>\r\n      <dependentAssembly>\r\n        <assembly" +
                    "Identity name=\"System.Web.WebPages\" publicKeyToken=\"31bf3856ad364e35\"/>\r\n       " +
                    " <bindingRedirect oldVersion=\"1.0.0.0-3.0.0.0\" newVersion=\"3.0.0.0\"/>\r\n      </d" +
                    "ependentAssembly>\r\n      <dependentAssembly>\r\n        <assemblyIdentity name=\"Sy" +
                    "stem.Web.Mvc\" publicKeyToken=\"31bf3856ad364e35\"/>\r\n        <bindingRedirect oldV" +
                    "ersion=\"1.0.0.0-5.2.2.0\" newVersion=\"5.2.2.0\"/>\r\n      </dependentAssembly>\r\n   " +
                    " </assemblyBinding>\r\n  </runtime>\r\n</configuration>\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 94 "C:\Users\Ahmed\Source\Repos\AppGenerator\WebApp\CSharpGenerator\Web\Configuration\WebConfig.tt"

    public string AppName{get;set;}
    public string DatabaseName{get;set;}
    public string ConnectionString{get;set;}
 
        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class WebConfigBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
